amazon-ion/ion-go

internal/lex/lex_binary.go, ion/parse_text_simple.go, ion/parse_text_test.go
Also adds escape processing in CLOB parsing to support `\xHH` escapes
which is part of #18.
#17 asks a larger question about the factoring around escape logic
in the parser, which this commit does not aim to address.
Fixes #3
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.
=> Fixes CLOB newline processing.

ion/parse_text.go, ion/parse_text_simple.go, ion/parse_text_test.go, ion/types_character.go
* Removes `unquoted` field and use of `strconv.Unquote` from `String`.
* Unifies `\x`, `\u`, and `\U` processing in `parse_text_simple.go`
for CLOB and String/Symbol.
Incremental improvement towards #17.  There is a bit more DRY than
I'd prefer in the String/Symbol switch statements, but I think it
is important to get these fixes out and address that more as a
follow-up for the lexer/parser refactor.
Depends on #19
Fixes #18
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.
=> Fixes String/Symbol hex escape processing.

README.md
Makes it clear that we use `goimports` for our style formatting
and provides some notes about how to go about setting this up
in one's dev environment.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.
=> Adds README content for `goimports`.

ion/integration_test.go, ion/reader_test.go
There is currently a test, reading the files in good directory of ion-test and construct a reader with them. Incorporate this test in `integration_test.go`.
=> Add TestReadGoodFiles in integration tests

.github/workflows/go.yml
Adds 2 steps to the build actions 
1. use `goimports` to format and check imports 
1. use `go lint` and report on linter errors 
=> chore(build): adds goimports and go lint github actions

README.md, ion/catalog_test.go, ion/fields.go, ion/marshal_test.go, ion/unmarshal_test.go
Resolves #63 
Given that users will be working with Ion, this change is more for clarity and moves away from the json tag to using the ion tag when marshalling and unmarshalling.
=> Moving from json tags to ion tags for Marshal/Unmarshal

ion/integration_test.go
Related #42 
Test is now passing. Might have been related to a previous fix or missed when verifying the skip list.
=> Enabling Float Length Too Long Test

ion/binarywriter.go, ion/textwriter.go, ion/writer.go
Resolves #71 
```writer.InStruct()``` is needed by Ion Hash, exposing it to external API.
=> Expose InStruct in ionWriter external api

ion/bitstream.go, ion/integration_test.go
Ion specs for [integer](http://amzn.github.io/ion-docs/docs/binary.html#2-and-3-int) reads:
> Zero is always stored as positive; negative zero is illegal.
=> Fix invalid negative int zero

cmd/ion-go/eventwriter.go, cmd/ion-go/process.go, ion/binaryreader.go, ion/binaryreader_test.go, ion/binarywriter.go, ion/bitstream.go, ion/consts.go, ion/integration_test.go, ion/reader.go, ion/textreader.go, ion/textreader_test.go, ion/textwriter.go, ion/unmarshal.go, ion/writer.go
1- Empty string is a valid value for field names.
Default value for strings in Go is empty string. Checking whether a fieldName is a set or not based on checking them against "", disallow us for having something like ```{"":empty}```.
One way to solve this issue is to change ```FieldName() string``` in Reader.go to ```FieldName() *string``` and set ```nil``` as ```reader.fieldName```'s default value in both ```textReader``` and ```binaryReader```. Then we will be able to change check if a fieldName is not set by ```r.fieldName != nil```. However, I do not think using nil as a magic value is a good idea in Go, and secondly changing return type of ```FieldName()``` is changing the API.
Alternatively in [this commit](https://github.com/amzn/ion-go/commit/d6c914ba3c51e8e144feddb6c4ab4104278701 …
=> Fix issues with struct

ion/fields.go, ion/marshal.go, ion/marshal_test.go
Encoder does not take annotations and consequently Marshal cannot serialize values with annotations.
To get the annotations when Marshalling, user should send a struct to Marshal() whereby one field of the struct is a slice of string and tagged as `ion:",annotations"`.
For instance:
```
type foo struct {
Value   int
AnyName []string `ion:",annotations"`
}
...
val := foo{5, []string{"age"}}
buf := MarshalText(val)
```
=> Add annotations when Marshalling values

ion/marshal_test.go
Omitting Symbols, Clob, and Time. Issues with all three types.
Time is pending PR from #98 
Symbols and Clob will be addressed later.
=> Adding Additional Marshal Unit Tests for Binary

ion/bitstream.go, ion/skipper.go, ion/textreader.go, ion/unmarshal.go
Resolves #131 
per https://github.com/golang/go/wiki/CodeReviewComments#error-strings error strings in go should not start with a capitalized word or end in punctuation
=> Normalize error messages

README.md
It was brought up by a user of Ion (QLDB), that having a direct link to Ion cookbook can be beneficial for someone who is not familiar with [ion-docs page](https://amzn.github.io/ion-docs/). 
That would allow the user to quickly see some code snippet on how to use Ion in some simple use cases.
=> Add Ion Cookbook link in README

ion/integration_test.go, ion/tokenizer.go
Resolves #134 
Text format Clob is limited to 7-bit ascii characters. To make clob values transcoding between binary and text format, we have to escape non 7-bit ascii characters in text format.
Some more explanation in [this comment](https://github.com/amzn/ion-tests/pull/27#issuecomment-299272704) on ion-test repository.
=> Handle clobs with escape sequence made up of 7-bit ASCII characters

ion/unmarshal.go
Resolves #110 
Define and allocate acceptable kinds for different Ion types once, to optimize the existing logic.
=> [Refactor] Make a single object for all different types acceptable kind

ion/unmarshal.go, ion/unmarshal_test.go
There are 2 commits in this pull request to improve Unmarshal:
- [Fix for unameshal string](https://github.com/amzn/ion-go/pull/166/commits/b02f30d8e63a76cdbd2babdefc4f4f22ecd6b833) : Using value of string when unmarshalling string into interface{} and fix some of the corresponding unit tests (the original change, roots in when returning type of [reader.string changed to a pointer](https://github.com/amzn/ion-go/pull/149/files#diff-47907c97adbd5c047dc4ec6220180178R493). 
- [Add null check](https://github.com/amzn/ion-go/pull/166/commits/3119673f3b87299180829d9bdf8da25cc336367d) : Setting nil to ```v.Set()``` can lead to error.
=> Fixes in unmarshal

go.mod, go.sum
Description of changes: Ran `go mod tidy` in anticipation of cutting a `v1.0.1` release.
=> go mod tidy for v1.0.1

ion/consts.go, ion/marshal.go, ion/marshal_test.go
Resolves #169
Currently, in order to Marshal a value of type ```Time```, one must create an ```ion.Timestamp``` using the ```Time``` value.
This PR is to enable passing a value of ```Time``` directly to Marshal.
```
// Currently:
val := NewTimestamp(time.Date(2010, 1, 1, 0, 0, 0, 0, time.UTC), TimestampPrecisionSecond, TimezoneUTC)
MarshalText(val)
// With this PR:
val = time.Date(2010, 1, 1, 0, 0, 0, 0, time.UTC)
MarshalText(val)
```
=> Marshal native Go Time

ion/unmarshal.go, ion/unmarshal_test.go
If the `map` value is a pointer type (e.g. `[]string`), `Unmarshal` produces invalid data because it overrides the values from previous keys.
For input `{headers:{key1:[val1],key2:[val2,val3],key3:[val4]}}` `Unmarshal` produces 
```go
&ion.request{Headers:map[string][]string{"key1":[]string{"val4"}, "key2":[]string{"val4", "val3"}, "key3":[]string{"val4"}}}
```
instead of
```go
&ion.request{Headers:map[string][]string{"key1":[]string{"val1"}, "key2":[]string{"val2", "val3"}, "key3":[]string{"val4"}}}
```
This change also fixes another bug from `v1.0.1` where `fieldName.Text` becomes `nil` after calling `d.decodeTo(subv)` because `fieldName` is a pointer and the value changes during reading other fields and structures. This bug has been fixed in in `v1.1.0` but it might be safer to save …
=> Fix Unmarshal for map of slices

ion/binarywriter.go, ion/cmp_test.go, ion/marshal.go, ion/skipper.go
Hey friends! I was testing out the setup of a new laptop by giving this a build and figured I'd fix a couple quick compiler warnings while I was in the neighborhood:
- Allocating an empty slice and then appending to it -> directly allocating the resulting slice
- `switch in.(type)` -> `switch in := in.(type)` to avoid a second typecheck/cast in the case statements
- casting an int to a string is discouraged because what it _actually_ does is string([]rune{rune(int)), but it looks like it's doing `strconv.Itoa(int)` (we had one of each :)).
=> address a few compiler warnings

go.mod, go.sum
This PR has the changes for `go mod tidy` for cutting `v1.1.1` release.
=> go mod tidy for v1.1.1

.github/workflows/go.yml
Issue #, if available:
N/A
CI Build workflow [is failing](https://github.com/amzn/ion-go/runs/5100341501?check_suite_focus=true) because something is broken in a non-standard github action for checking out submodules that we are depending on. This commit replaces the non-standard github action with the correct configuration in the Github-provided checkout action.
=> Fixes CI build workflow

ion/unmarshal.go, ion/unmarshal_test.go
Issue #, if available: #184
Adds the unmarshalling equivalent of `Marshaler`. Allowing types to implement their own unmarshalling logic. It's basically the same implementation, but requires the `UnmarshalIon` method to be implemented with a pointer receiver as it needs to mutate the struct.
=> #184: Allow custom unmarshal implementation

.github/workflows/go.yml, .gitmodules, README.md, cmd/ion-go/eventwriter.go, cmd/ion-go/main.go, cmd/ion-go/nopwriter.go, cmd/ion-go/process.go, cmd/ion-go/schema.go, cmd/ion-go/util.go, go.mod, ion/binarywriter.go, ion/decimal.go, ion/fields.go, ion/integration_test.go, ion/marshal.go, ion/reader.go, ion/skipper.go, ion/tokenizer.go, ion/unmarshal.go, ion/unmarshal_test.go, ion/writer.go, scripts/build.sh, scripts/install.sh
**Issue #, if available:**
None
**Description of changes:**
There are 3 commits:
* Changes `amzn` to `amazon-ion` in links
* Replaces a broken github action that we were using with a new lint check that works
* Example of the new lint check failing: https://github.com/popematt/ion-go/actions/runs/4067936206/jobs/7005874857d
* Updated `actions/checkout` to v3 while I was at it, and cleaned up some extraneous whitespace in the workflow file.
* Fixes all of the formatting issues
* For some unknown reason, `gofmt`/`goimports` things that `'''` must be replaced by `”'` in all Godoc comments, so I reworded most comments to avoid having `'''`, except for the function that is specifically for recognizing `'''`, where I added a code block to contain the `'''`.
* All of the remaining changes were …
=> Fix CI workflow, formatting, and GitHub org name

ion/marshal.go, ion/marshal_test.go, ion/type.go
This is intended to be a fix for https://github.com/amazon-ion/ion-go/issues/193. ion.MarshalText() returns "{}" for math/big.Int values.
Added BigIntType in type.go. Created func encodeBigInt() in marshal.go and added it to encodeStruct(). Also added unit tests for math/big.Int in marshal_test.go.
=> Fix math/big.Int Does not Marshal

ion/binaryreader.go, ion/binaryreader_test.go
Reset improves reader performance when the same binary data is processed multiple times. It works by reusing the symbol table constructed during the first read, and jumping straight to the first "content" byte when Reset is called.
=> Add Reset function to binaryReader
