README.md
ion/parse_binary_test.go
ion/parse_text_test.go

Adds skip lists and references for breaking changes
to the tests
See: #3, #4
Resolves #1
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

Updates ion-tests to HEAD.

---

ion/type.go
ion/type_test.go

Resolves https://github.com/amzn/ion-go/issues/34

Implement isScalar() and isContainer() in type.go

---

ion/textwriter.go
ion/textwriter_test.go

Adding support for pretty-printing text Ion

---

ion/integration_test.go

Minor improvement in logging for equivalency tests

Add more logging for equivalency test

---

ion/bitstream.go

Ordered structs in binary encoding are presented with ```D1```, and the size of that struct comes in the byte after ```D1```.

Binary ordered structs

---

ion/bitstream.go
ion/integration_test.go

This fix is to detect strings with latine-1 (ISO-8859-1) characters.

String with ISO-8859-1 characters

---

ion/integration_test.go

Update tests' skip lists

---

ion/bitstream.go

To address [this comment](https://github.com/amzn/ion-go/pull/86#discussion_r447920472).

Update state when reading empty lob issue

---

ion/unmarshal_test.go

Expand unit testing on Unmarshal - Ion binary test data

Add tests to Unmarshal for Ion binary

---

ion/marshal.go

There has been some suggestions on #104 after merge. This pull request is to address them

Minor changes on Marshal

---

cmd/ion-go/main.go
cmd/ion-go/process.go
cmd/ion-go/util.go
ion/marshal.go
ion/skipper.go
ion/symboltable.go
ion/textwriter.go
ion/tokenizer.go

Adding error handling for functions which return `error`

unhandled errors

---

ion/catalog.go
ion/integration_test.go
ion/reader.go
ion/textreader_test.go
ion/unmarshal.go
ion/unmarshal_test.go

update ```UnmarshaStr``` and ```NewReaderStr``` to ```UnmarshalString``` and ```NewReaderString```.

update UnmarshaStr and NewReaderStr to UnmarshalString and NewReaderString

---

ion/marshal.go
ion/unmarshal.go

This is not for Preview
----
This pull request is to improve documentation on Marshal and Unmarshal

Improve documentation on Marshal and Unmarshal

---

README.md

* Adds a users section to the readme to links of other products build using ion-go

docs: adds user section in readme:

---

ion/integration_test.go
ion/textreader.go
ion/tokenizer.go

Fix S-Expression Tests

---

ion/integration_test.go

One test in specific, ```documents.ion``` has a different format for its embedded_documents test.
I updated our testing to accommodate for different types of tests with embedded_documents annotation.

Update integration_test for embedded_documents tests

---

README.md
ion/symboltable.go
ion/symboltable_test.go
ion/symboltoken.go
ion/symboltoken_test.go

Create SymbolToken and incorporate to SymbolTable

---

ion/binarywriter.go
ion/bitstream.go
ion/cmp_test.go
ion/decimal.go
ion/integration_test.go

Handle Negative Zero Decimal

---

cmd/ion-go/process.go
ion/cmp_test.go
ion/integration_test.go
ion/reader.go
ion/readlocalsymboltable.go
ion/textreader_test.go
ion/unmarshal.go
ion/unmarshal_test.go

Resolves #152 
As #152 explains, this pull request is to update Reader api interface.

Reader api change

---

cmd/ion-go/process.go
ion/binaryreader_test.go
ion/integration_test.go
ion/reader.go
ion/textreader_test.go
ion/type.go

Resolves https://github.com/amzn/ion-go/issues/102

Remove Uint64 int type

---

ion/skipper.go
ion/textreader.go
ion/textreader_test.go
ion/tokenizer.go

This pull request contains some refactoring for reading Clobs:
- Separates reading of clob from string, which Resolves #144; done in this commit: b9a8adf
- Simplifies the logic for reaching at the end of a long string which Resolves #61; done in this commit: 9918dcb

Clob refactoring

---

ion/unmarshal.go
ion/unmarshal_test.go

Addresses QLDB driver issue https://github.com/awslabs/amazon-qldb-driver-go/issues/56.

Support Timestamp to Time decoding

---

ion/decimal.go
ion/decimal_test.go

Issue #176:
Add `UnmarshalJSON` and `MarshalJSON` to `Decimal`

add UnmarshalJSON and MarshalJSON to Decimal
